#!/usr/bin/env php
<?php
    require __DIR__.'/vendor/autoload.php';    
    use Illuminate\Support\Pluralizer;
    
    $o = fopen('php://output');
  
    if (sizeof($_SERVER['argv'])==1){ //no arg was given
        return 0;
    } 
    $a = $_SERVER['argv'][1];
    $p = Pluralizer::plural($a); 
    fwrite($o, $p);

    fwrite($o, "\n");
?>
